// cmd/apigen/main.go generates web/src/api.generated.js from Go response types.
// Run: go run ./cmd/apigen
// The output is committed to git so the frontend build has no Go dependency.
package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

type Field struct {
	GoName   string `json:"go_name"`
	JSONName string `json:"json_name"`
	Type     string `json:"type"`
	Optional bool   `json:"optional,omitempty"`
}

type TypeDef struct {
	Name   string  `json:"name"`
	Fields []Field `json:"fields"`
}

// Source files and types to extract
var sources = []struct {
	file  string
	types []string
}{
	{"internal/store/route_decisions.go", []string{"RouteDecisionEntry", "RouteDecisionCandidate"}},
	{"internal/store/store.go", []string{"RequestRow"}},
	{"internal/store/billing.go", []string{"BillingStatus"}},
	{"internal/store/groups.go", []string{"Group", "GroupMember"}},
}

func main() {
	root := findProjectRoot()
	var allTypes []TypeDef

	for _, src := range sources {
		path := filepath.Join(root, src.file)
		types, err := extractTypes(path, src.types)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARN: %s: %v\n", src.file, err)
			continue
		}
		allTypes = append(allTypes, types...)
	}

	output := generateJS(allTypes)
	outPath := filepath.Join(root, "web/src/api.generated.js")
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s (%d types, %d fields)\n", outPath, len(allTypes), countFields(allTypes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "ERROR: cannot find go.mod")
			os.Exit(1)
		}
		dir = parent
	}
}

func extractTypes(filename string, typeNames []string) ([]TypeDef, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	wanted := make(map[string]bool)
	for _, n := range typeNames {
		wanted[n] = true
	}

	var result []TypeDef
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || !wanted[ts.Name.Name] {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		td := TypeDef{Name: ts.Name.Name}
		for _, field := range st.Fields.List {
			if field.Tag == nil {
				continue
			}
			tag := reflect.StructTag(strings.Trim(field.Tag.Value, "`"))
			jsonTag := tag.Get("json")
			if jsonTag == "" || jsonTag == "-" {
				continue
			}
			parts := strings.Split(jsonTag, ",")
			jsonName := parts[0]
			optional := false
			for _, p := range parts[1:] {
				if p == "omitempty" {
					optional = true
				}
			}
			goType := typeString(field.Type)
			for _, name := range field.Names {
				td.Fields = append(td.Fields, Field{
					GoName:   name.Name,
					JSONName: jsonName,
					Type:     goType,
					Optional: optional,
				})
			}
		}
		result = append(result, td)
		return true
	})
	return result, nil
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.ArrayType:
		return "[]" + typeString(t.Elt)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.MapType:
		return "map"
	case *ast.InterfaceType:
		return "any"
	default:
		return "unknown"
	}
}

func generateJS(types []TypeDef) string {
	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by cmd/apigen — do not edit manually.\n")
	b.WriteString("// Source: Go struct json tags → frontend field contract.\n")
	b.WriteString("// Regenerate: go run ./cmd/apigen\n\n")

	// Export field name constants per type
	for _, td := range types {
		b.WriteString(fmt.Sprintf("/** @typedef {Object} %s\n", td.Name))
		for _, f := range td.Fields {
			jsType := goTypeToJS(f.Type)
			opt := ""
			if f.Optional {
				opt = "="
			}
			b.WriteString(fmt.Sprintf(" * @property {%s%s} %s\n", jsType, opt, f.JSONName))
		}
		b.WriteString(" */\n\n")

		// Field name constants
		constName := camelToScreamingSnake(td.Name)
		b.WriteString(fmt.Sprintf("export const %s_FIELDS = Object.freeze({\n", constName))
		for _, f := range td.Fields {
			b.WriteString(fmt.Sprintf("  %s: '%s',\n", f.GoName, f.JSONName))
		}
		b.WriteString("})\n\n")
	}

	// Envelope unwrapper
	b.WriteString(`/**
 * Unwrap API response envelope. Lists come as {items: [...]}, details as plain objects.
 * @template T
 * @param {Object} raw - Raw fetch response JSON
 * @returns {T[]|T}
 */
export function unwrap(raw) {
  if (raw && Array.isArray(raw.items)) return raw.items
  if (raw && typeof raw === 'object' && !Array.isArray(raw)) return raw
  return raw
}

`)

	// Timestamp normalizer
	b.WriteString(`/**
 * Normalize a timestamp to milliseconds. Handles unix seconds, milliseconds, and ISO strings.
 * @param {number|string|null} ts
 * @returns {number|null} milliseconds since epoch, or null
 */
export function normalizeTs(ts) {
  if (ts == null || ts === 0) return null
  if (typeof ts === 'string') return new Date(ts).getTime()
  // Unix seconds (10 digits) vs milliseconds (13 digits)
  return ts < 1e12 ? ts * 1000 : ts
}

`)

	// Dev-mode validator
	b.WriteString(`const DEV = import.meta.env?.DEV ?? false

/**
 * Validate an object against expected fields (dev-mode only, no-op in production).
 * Logs warnings for missing required fields.
 * @param {string} typeName
 * @param {Object} obj
 * @param {Object} fieldsConst - FIELDS constant for the type
 */
export function validate(typeName, obj, fieldsConst) {
  if (!DEV || !obj) return
  const expected = Object.values(fieldsConst)
  const actual = Object.keys(obj)
  const missing = expected.filter(f => !actual.includes(f) && !f.startsWith('actual_'))
  if (missing.length > 0) {
    console.warn('[api-contract]', typeName, 'missing fields:', missing.join(', '))
  }
}
`)

	// Generate adapter for RouteDecisionEntry
	b.WriteString(`
/**
 * Adapt a route decision from API response to component-friendly shape.
 * @param {RouteDecisionEntry} raw
 * @returns {Object}
 */
export function adaptRouteDecision(raw) {
  return {
    ...raw,
    created_at_ms: normalizeTs(raw.created_at),
    completed_at_ms: normalizeTs(raw.completed_at),
  }
}
`)

	return b.String()
}

func goTypeToJS(goType string) string {
	switch {
	case goType == "string" || goType == "*string":
		return "string"
	case goType == "int64" || goType == "int" || goType == "float64" || goType == "*float64" || goType == "*int64":
		return "number"
	case goType == "bool":
		return "boolean"
	case strings.HasPrefix(goType, "[]"):
		inner := goTypeToJS(goType[2:])
		return inner + "[]"
	case goType == "map" || goType == "any":
		return "Object"
	default:
		return "Object"
	}
}

func camelToScreamingSnake(s string) string {
	var result []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, r)
	}
	return strings.ToUpper(string(result))
}

func countFields(types []TypeDef) int {
	n := 0
	for _, t := range types {
		n += len(t.Fields)
	}
	return n
}

// Ensure deterministic output
func init() {
	_ = sort.Strings
	_ = json.Marshal
}
