-- Model mapping table: static aliases and auto-learned fallbacks.
-- Supports per-upstream and global (upstream_id=0) mappings.
-- Auto-learned mappings have a TTL (expires_at) for periodic re-probing.

CREATE TABLE IF NOT EXISTS model_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upstream_id BIGINT NOT NULL DEFAULT 0,
    source_model TEXT NOT NULL,
    target_model TEXT NOT NULL,
    mapping_type TEXT NOT NULL DEFAULT 'static',
    failure_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (upstream_id, source_model)
);

CREATE INDEX IF NOT EXISTS idx_model_mappings_source ON model_mappings(source_model);
CREATE INDEX IF NOT EXISTS idx_model_mappings_upstream ON model_mappings(upstream_id, source_model);
CREATE INDEX IF NOT EXISTS idx_model_mappings_expires ON model_mappings(expires_at) WHERE expires_at IS NOT NULL;
